# HTTP 服务端口号
server.port = 8080

# 应用的上下文路径, 空表示根路径
server.servlet.context-path=

# 应用名称
spring.application.name=spring-boot-demo

# Redis连接配置
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.database=0
# 设置连接到Redis服务器的超时时间
spring.redis.connect-timeout=5s
# 设置进行Redis操作的超时时间
spring.redis.timeout=5s

# jedis连接池配置（当使用jedis作为Redis客户端时生效）
# 指定连接池中最小空闲连接数。默认为0，表示不维持最小空闲连接。
spring.redis.jedis.pool.min-idle=0
# 指定连接池中最大空闲连接数。默认为8。
spring.redis.jedis.pool.max-idle=8
# 指定连接池中最大活动连接数。默认为8，超过此数的连接请求将等待。
spring.redis.jedis.pool.max-active=8
# 指定连接池中最大等待时间。-1表示永远等待。默认为-1ms。
spring.redis.jedis.pool.max-wait=-1ms

